package main

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite the golden files")

func TestRenderStep(t *testing.T) {
	got := string(renderStep(testSpec(), 0))
	for _, want := range []string{
		"<!-- Generated by tattva from spec.json.",
		"# 01 · Create run.sh",
		"Phase 1: Setup · Concepts: program-contract, tcp-sockets",
		"## Your task",
		"- standard library only",
		"<details><summary>Machine checks (run by the verifier)</summary>",
		"**accepts a connection**: send `\"PING\\r\\n\"`",
		"<details><summary>Hint 1 (nudge)</summary>",
		"<details><summary>Hint 3 (pseudocode)</summary>\n\n```text\nlisten on 6379; loop: accept a connection\n```\n\n</details>",
		"</details>\n\n## Common mistakes",
		"## Unlocks\n\n- 02 · Respond to PING",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("step file missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "<no value>") {
		t.Errorf("template printed <no value>:\n%s", got)
	}
}

func TestRenderReadme(t *testing.T) {
	got := string(renderReadme(testSpec()))
	for _, want := range []string{
		"# Mini Redis",
		"**Target:** Redis · **Language:** go",
		"- **persistence**: not needed to learn the protocol",
		"```mermaid\nflowchart LR\n  server --> parser\n```",
		"wait for port 6379",
		"- **Message framing** (`message-framing`): ",
		"- [RESP spec](https://redis.io/docs/latest/develop/reference/protocol-spec/)",
		"### Phase 2: Protocol",
		"- **02 · Respond to PING**: Reply +PONG to PING. *(after 01)* *(not expanded yet)*",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("README missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "<no value>") {
		t.Errorf("template printed <no value>:\n%s", got)
	}
}

func TestDescribeCheck(t *testing.T) {
	for _, tc := range []struct {
		c    Check
		want string
	}{
		{Check{Name: "init", Do: "exec", Args: []string{"init"}, Match: "exact"}, "**init**: run `./run.sh init`, expect exit code 0"},
		{Check{Name: "pong", Do: "tcp", Input: "PING\r\n", Expect: "+PONG\r\n", Match: "exact"}, "**pong**: send `\"PING\\r\\n\"`, expect reply `\"+PONG\\r\\n\"` (exact)"},
		{Check{Name: "fixture", Do: "write", Path: "a.txt", Input: "hi", Match: "exact"}, "**fixture**: write `\"hi\"` to `a.txt`"},
		{Check{Name: "head", Do: "file", Path: ".git/HEAD", Expect: "ref: refs/heads/main\n", Match: "exact"}, "**head**: `.git/HEAD` exists with content `\"ref: refs/heads/main\\n\"` (exact)"},
		{Check{Name: "commit", Do: "exec", Args: []string{"commit", "-m", "it's done"}, Match: "exact"}, "**commit**: run `./run.sh commit -m 'it'\\''s done'`, expect exit code 0"},
		{Check{Name: "hash", Do: "exec", Args: []string{"hash-object", "a.txt"}, Expect: `^[0-9a-f]{40}\n$`, Match: "regex"}, "**hash**: run `./run.sh hash-object a.txt`, expect exit code 0 and stdout `^[0-9a-f]{40}\\n$` (regex)"},
		{Check{Name: "big", Do: "write", Path: "big.txt", Input: strings.Repeat("a", 500), Match: "exact"}, "**big**: write `\"" + strings.Repeat("a", 120) + "\"`… (500 bytes) to `big.txt`"},
	} {
		if got := describeCheck(tc.c); got != tc.want {
			t.Errorf("describeCheck(%s) = %q, want %q", tc.c.Name, got, tc.want)
		}
	}
}

func TestRenderGolden(t *testing.T) {
	s := testSpec()
	for name, got := range map[string][]byte{"README.md": renderReadme(s), "step-01.md": renderStep(s, 0)} {
		path := filepath.Join("testdata", "golden", name)
		if *update {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, got, 0o644); err != nil {
				t.Fatal(err)
			}
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("%v (run `go test ./... -run TestRenderGolden -update` to create it)", err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s differs from its golden file; rerun with -update if the change is intended\n%s", name, got)
		}
	}
}

func TestRenderFencesPseudocodeOnce(t *testing.T) {
	s := testSpec()
	s.Steps[0].Detail.Hints[2] = "```go\nfor {}\n```"
	got := string(renderStep(s, 0))
	if strings.Contains(got, "```text") || !strings.Contains(got, "```go\nfor {}\n```") {
		t.Fatalf("an already fenced hint must be left alone:\n%s", got)
	}
}
